config/routes.rb
Rails.application.routes.draw do
  
  
  resources :books do
    resources :comments, shallow: true, only: [ :create , :destroy ]
  end
  resource :users, except: [ :destroy ] do
    collection do
      get :sign_in
    end
  end

  resource :sessions, only: [ :create , :destroy ]
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :price, numericality: { greate_than: 0 }

  belongs_to :user
  has_many :comments, -> { order(id: :desc)}

  default_scope { where(deleted_at: nil) }

  def destroy
    update(deleted_at: Time.current)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true

  has_many :books
  has_many :comments
  before_create :encrypt_password


  def own?(b)
    book_ids.include?(b.id)
  end

  def encrypt_password
    salted_password = "*xx#{self.password}yy-"
    self.password = Digest::SHA256.hexdigest(salted_password)
  end
  
  def self.login(data)
    email = data[:email]
    password = Digest::SHA256.hexdigest("*xx#{data[:password]}yy-")

    find_by(email:, password:)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  helper_method :current_user, :user_signed_in?
  private

  def not_found
    render file: Rails.public_path.join('404.html'),status: 404, layout: false
  end

  def current_user
    @__user__ || User.find_by(id: session[:__user_ticket__])
  end

  def user_signed_in?
    current_user.present?
  end

  def authenticate_user!
    if not user_signed_in?
      redirect_to sign_in_users_path, alert: '請先登入帳號'
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [ :show ]
  before_action :authenticate_user!, except: [ :index , :show ]
  before_action :find_owned_book, only: [ :edit , :update , :destroy ]

  def index
    @books = Book.order(id: :desc)
  end

  def new
    @book = Book.new
  end

  def create
    # @book = Book.new(book_params)
    @book = current_user.books.new(book_params)
    if @book.save
      redirect_to root_path, notice: '新增成功'
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @book.comments
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to root_path(@book), notice: '編輯成功'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path, alert: '刪除成功'
  end

  private

  def find_book
    @book = Book.find(params[:id])
  end

  def find_owned_book
    @book = current_user.books.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :description, :price, :onsale)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    book = Book.find(params[:book_id])
    comment = book.comments.new(comment_params)

    if comment.save
      redirect_to book_path(book), notice: '新增連言成功'
    else
      redirect_to book_path(book), alert: '留言發生錯誤'
    end
  end

  

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user: current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    # render html:params
    user = User.login(params[:user])

    if user
      session[:__user_ticket__] = user.id
      redirect_to root_path, notice: '登入成功'
    else
      redirect_to sign_in_users_path, alert: '登入失敗'
    end
  end

  def destroy
    session.delete(:__user_ticket__)
    redirect_to root_path, notice: '登出成功'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: '註冊成功'
    else
      render :new
    end
  end


  def sign_in
    
  end

  

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  

end

app/views/books/_form.html.erb
<% if book.errors.any? %>
  <section>
    <ul>
      <% book.errors.full_messages.each do | message | %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>
<%= form_with model: book, data:{ turbo: false } do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :price %>
    <%= f.number_field :price , min: 0 %>
  </div>

  <div>
    <%= f.label :onsale %>
    <%= f.check_box :onsale %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/books/edit.html.erb
<h1>編輯書籍</h1>

<%= render 'form', book: @book %>

app/views/books/index.html.erb
<h1 class="text-2xl">書籍列表</h1>


<% @books.each do |book| %>

  <%= link_to book.title, book_path(book) %>

<% end %>

app/views/books/new.html.erb
<h1>新增書籍</h1>

<%= render 'form', book: @book %>

app/views/books/show.html.erb
<% if user_signed_in? and current_user.own?(@book) %>
  <%= link_to "編輯", edit_book_path %>
  <%= link_to "刪除", book_path(@book), data: { turbo_method: 'delete',
                                              turbo_confirm: '確定要刪除嗎？'} %>
<% end %>



<h1><%= @book.title %></h1>
<h3><%= @book.price %></h3>
<p><%= @book.description %></p>


<section>
  <h3>留言</h3>

  <%= form_with( model: [@book, @comment], data: { turbo: false }) do |f| %>
    <%= f.text_area :content %>
    <div>
      <%= f.submit '新增留言' %>
    </div>
  <% end %>


  <ul>
    <% @comments.each do |comment| %>
      <li><%= comment.content %></li>
    <% end %>
  </ul>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Star</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash' if flash.any? %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% [:notice, :alert].each do |type| %>
  <% if flash[type] %>
    <div class="flash-<%= type %>">
      <%= flash[type] %>
    </div>
  <% end %>
<% end %>

app/views/shared/_form.html.erb
<% if book.errors.any? %>
  <section>
    <ul>
      <% book.errors.full_messages.each do | message | %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>
<%= form_with model: book, data:{ turbo: false } do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div>
    <%= f.label :onsale %>
    <%= f.check_box :onsale %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/shared/_navbar.html.erb
<nav
  class="flex items-center justify-between px-3 py-2 text-white bg-slate-800"
>
  <div class="flex items-center gap-2">
    <h1 class="text-2xl font-bold"><%= link_to "閃亮書店",root_path %></h1>
    <ul class="flex gap-3">
      <li><%= link_to "書籍列表", books_path %></li>
      <% if user_signed_in? %>
      <li><%= link_to "新增書籍", new_book_path %></li>
      <% end %>
    </ul>
  </div>
  <div>
    <ul class="flex gap-3">
      <% if user_signed_in? %>
        <li><%= current_user.email %></li>
        <%= link_to '登出', sessions_path, data: { turbo_method: 'delete' } %>
      <% else %>
        <li><%= link_to '註冊', new_users_path %></li>
        <li><%= link_to '登入', sign_in_users_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/new.html.erb
<h1>註冊會員</h1>

<%= form_with model: @user, data: { turbo: false } do |f| %>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <div><%= f.submit '註冊會員'%></div>
<% end %>

app/views/users/sign_in.html.erb
<h1>登入帳號</h1>

<%= form_with( url: sessions_path,
                    scope: 'user',
                    data: { turbo: false }) do |f| %>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'input-field' %>
  </div>

  <div>
    <%= f.submit '登入'%>
  </div>

<% end %>